name: DaFlightManager
main: me.dags.daflightmanager.DaFlightManager
version: ${project.version}-r${buildNumber}
author: dags_
softdepend: [NoCheatPlus]
website: ${project.url}

permissions:
  DaFlight.user:
    default: op
    children:
      DaFlight.fullbright: true
      DaFlight.flymod: true
      DaFlight.speed.3: true
  DaFlight.mod:
    default: op
    children:
      DaFlight.fullbright: true
      DaFlight.flymod: true
      DaFlight.speed.7: true
  DaFlight.admin:
    default: op
    children:
      DaFlight.fullbright: true
      DaFlight.flymod: true
      DaFlight.speed.13: true
  DaFlight.*:
    default: op
    children:
      DaFlight.fullbright: true
      DaFlight.flymod: true
      DaFlight.speed.50: true
  DaFlight.fullbright:
    description: Allow user to use DaFlight's fullbright
    default: op
  DaFlight.flymod:
    description: Allow user to use DaFlight's flymod
    default: op
  DaFlight.softfall:
    description: User doesn't take fall damage whilst flying
    default: op
  DaFlight.speed.2:
    default: op
  DaFlight.speed.3:
    default: op
  DaFlight.speed.5:
    default: op
  DaFlight.speed.7:
    default: op
  DaFlight.speed.10:
    default: op
  DaFlight.speed.13:
    default: op
  DaFlight.speed.15:
    default: op
  DaFlight.speed.25:
    default: op
  DaFlight.speed.50:
    default: op